runtime! debian.vim

filetype off   

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'mattn/emmet-vim'

call vundle#end()
filetype plugin indent on

au BufRead,BufNewFile *.js set et sts=2 sw=2
au BufRead,BufNewFile *.html set et sts=2 sw=2
au BufRead,BufNewFile *.scss set et sts=2 sw=2
au BufRead,BufNewFile *.css set et sts=2 sw=2

syntax on
set number
set winminheight=0
set winheight=99
